baseurl = "https://www.thewatersabove.org/"
languageCode = "en-us"
title = "The Waters Above"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
# Define the number of posts per page
paginate = 10
footnotereturnlinkcontents = "↩"
theme = "hugo-icarus"
# Comment the themesDir option if you use this theme in production

[permalinks]
    post = "/:year/:month/:day/:slug"

[params]
    # Tell me who you are
    author = "The Waters Above"
    bio = "Enlightening the world through music"
    location = "Bigfork, Montana"
    site_description = "Free Your Mind"
    copyright  = "The Waters Above"
    avatar = "images/waters-above-square-13.svg"
    # Enter your email address to display your Gravatar icon in the profile. If not set the theme
    # will fallback to the avatar.
    gravatar = "thewatersabove@protonmail.com"
    logo = "images/waters-above-logo-8-tight.png"
    #logo = "resources/img/waters-above-logo.png"
    disable_mathjax = false # set to true to disable MathJax

    # define which types of pages should be shown. By default the type with the most regular pages
    mainSections = ["post"]

    # Format dates with Go's time formatting
    date_format = "2006-01-02"

    # Add custom assets with their paths relative to the static folder
	custom_css = ["css/thewatersabove.css"]
	custom_js  = []

# Create custom menu entries by defining a label and a link for
# them. Since you can also link posts, you've the option the
# place the links before or after them.
#
# E.g.: "Home" appears before all linked posts in the menu
# and "Tags" / "Categories" after them.

# [[params.menu]]
#     before = true
#     label  = "Home"
#     link   = "/"

[[params.menu]]
    before = true
    label  = "About"
    link   = "about/"

[[params.menu]]
    before = false
    label  = "Blog"
    link   = "blog/"

[[params.menu]]
    before = false
    label  = "Music"
    link   = "songs/"

[[params.menu]]
    before = false
    label  = "Tour"
    link   = "shows/"

[[params.menu]]
    before = false
    label  = "Contribute"
    link   = "contribute/"

# [[params.menu]]
#     before = false
#     label  = "Store"
#     link   = "store/"

[[params.menu]]
    before = false
    label  = "Contact"
    link   = "contact/"

[social]
# Add your social network accounts to the profile section on the left
# by entering your username. The links to your account will be
# created automatically.
    github          = ""
    gitlab          = ""
    bitbucket       = ""
    jsfiddle        = ""
    codepen         = ""
    foursquare      = ""
    dribbble        = ""
    deviantart      = ""
    behance         = ""
    flickr          = ""
    instagram       = "watersaboveband"
    youtube         = "channel/UCyAu066wppmIsy0w9CnnfRw"
    vimeo           = ""
    vine            = ""
    medium          = ""
    wordpress       = ""
    tumblr          = ""
    xing            = ""
    linkedin        = ""
    slideshare      = ""
    stackoverflow   = ""
    reddit          = ""
    pinterest       = ""
    googleplus      = ""
    facebook        = ""
    facebook_admin  = ""
    twitter_domain  = ""
    twitter         = "watersaboveband"

# Enter a link for the follow button on the left
[params.profile]
    follow_button = "//eepurl.com/hZU-X5"

# Enable and disable widgets for the right sidebar
[params.widgets]
    recent_articles = true
    categories = true
    tags = true
    tag_cloud = true
